#!/bin/bash
echo ---------------------------------

date

paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'

echo verificación de las temperaturas

echo ---------------------------------

